Feature/5 api implement db
thestahan/Tournament4You pull request #9
Opened 2022-04-03 13:27 UTC by chainowsky

2022-04-03 14:54 UTC, thestahan requested changes
Looks great, only some minor formatting issues need to be addressed.

2022-04-03 14:54 UTC, thestahan commented on API/Data/ApiDbContext.cs
> +
Let's leave only one blank line here

2022-04-03 14:54 UTC, thestahan commented on API/Domain/Position.cs
> +
Let's stick to the version with no blank lines between "normal" properties and ICollection

2022-04-03 14:54 UTC, thestahan commented on API/Domain/Team.cs
> +
As above

2022-04-03 14:54 UTC, thestahan commented on API/Domain/Team.cs
> +
Here's also an unnecessary line

2022-04-03 14:54 UTC, thestahan commented on API/Data/ApiDbContext.cs
> +        public DbSet<Match> Matches => Set<Match>();
For better clarity, we should always leave one blank line between methods and other things; tldr: add one blank line above

2022-04-04 13:31 UTC, chainowsky reviewed
improved

2022-04-04 15:46 UTC, thestahan approved these changes

2022-04-04 15:48 UTC, merged